name: Python Security Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: false
        default: '3.11'
        type: string
      source-dir:
        description: 'Source directory'
        required: false
        default: '.'
        type: string
      requirements-file:
        description: 'Requirements file path'
        required: false
        default: ''
        type: string
      test-dir:
        description: 'Test directory'
        required: false
        default: 'tests'
        type: string
      bandit-severity:
        description: 'Bandit severity level'
        required: false
        default: 'll'
        type: string
      fail-on-security-issues:
        description: 'Fail if security issues found'
        required: false
        default: true
        type: boolean
    outputs:
      security-status:
        description: 'Security scan status'
        value: ${{ jobs.python-scan.outputs.security-status }}

jobs:
  python-scan:
    runs-on: ubuntu-latest
    outputs:
      security-status: ${{ steps.security.outputs.status }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python dependencies and tools
      uses: ./.github/actions/setup-dependencies/python
      with:
        python-version: ${{ inputs.python-version }}
        requirements-file: ${{ inputs.requirements-file }}
        install-security-tools: 'true'
    
    - name: Run Bandit security scan
      id: security
      working-directory: ${{ inputs.source-dir }}
      run: |
        bandit -r . -${{ inputs.bandit-severity }} || exit_code=$?
        if [ "${{ inputs.fail-on-security-issues }}" = "true" ] && [ "${exit_code:-0}" -ne 0 ]; then
          exit $exit_code
        fi
        echo "status=completed" >> "$GITHUB_OUTPUT"
    
    - name: Run tests if specified
      if: inputs.test-dir != ''
      working-directory: ${{ inputs.source-dir }}
      run: |
        pytest ${{ inputs.test-dir }} || true