name: Setup Dependencies and Cache
description: Install system dependencies and setup caching for CPP and Python

runs:
  using: composite
  
  steps:
  - name: Install system dependencies
    shell: bash
    run: |
      sudo apt-get update
      sudo apt-get install -y cmake ninja-build build-essential

  - name: Cache CMake build
    uses: actions/cache@v4
    with:
      path: build
      key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt') }}
      restore-keys: |
        ${{ runner.os }}-cmake-
  
  - name: Set up Python 3.11
    uses: actions/setup-python@v5
    with:
      python-version: '3.11'

  - name: Cache pip
    uses: actions/cache@v4
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('service/**/requirements*.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install Python dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      if [ -f service/requirements.txt ]; then pip install -r service/requirements.txt; fi