name: Bandit Security Code Scanning

on:
  workflow_call:
    inputs:
      scan-path:
        description: 'Path to scan'
        required: false
        default: '.'
        type: string
      confidence-level:
        description: 'Confidence level'
        required: false
        default: 'medium'
        type: string
      severity-level:
        description: 'Severity level'
        required: false
        default: 'medium'
        type: string
      exclude-paths:
        description: 'Paths to exclude'
        required: false
        default: ''
        type: string
      upload-sarif:
        description: 'Upload SARIF results'
        required: false
        default: true
        type: boolean

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Bandit
      run: pip install bandit[sarif]
    
    - name: Run Bandit scan
      run: |
        EXCLUDE_ARGS=""
        if [ -n "${{ inputs.exclude-paths }}" ]; then
          EXCLUDE_ARGS="--exclude ${{ inputs.exclude-paths }}"
        fi
        
        bandit -r ${{ inputs.scan-path }} \
          --confidence-level ${{ inputs.confidence-level }} \
          --severity-level ${{ inputs.severity-level }} \
          $EXCLUDE_ARGS \
          -f sarif -o bandit-results.sarif
      continue-on-error: true
    
    - name: Upload SARIF results
      if: inputs.upload-sarif
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: bandit-results.sarif