name: CMake/C++ Security Workflow
description: Reusable workflow for C++ projects with CMake

on:
  workflow_call:
    inputs:
      build-type:
        description: 'CMake build type'
        required: false
        default: 'Release'
        type: string
      source-dir:
        description: 'Source directory'
        required: false
        default: '.'
        type: string
      build-dir:
        description: 'Build directory'
        required: false
        default: 'build'
        type: string
      cmake-args:
        description: 'Additional CMake arguments'
        required: false
        default: ''
        type: string
      upload-artifacts:
        description: 'Upload build artifacts'
        required: false
        default: true
        type: boolean
    outputs:
      artifact-name:
        description: 'Name of the uploaded artifact'
        value: ${{ jobs.cmake-security.outputs.artifact-name }}
      build-status:
        description: 'Build status'
        value: ${{ jobs.cmake-security.outputs.build-status }}

jobs:
  cmake-security:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact.outputs.name }}
      build-status: ${{ steps.build.outputs.status }}
    
    steps:
    - name: Checkout calling repository code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
    
    - name: Checkout security actions repository
      uses: actions/checkout@v4
      with:
        repository: rmtechtransfer1/github-actions-security
        path: security-actions  # Simpler path
        ref: main
    
    # Now use the correct path to the action
    - name: Setup C++ dependencies and tools
      uses: ./security-actions/.github/actions/setup-dependencies/c++
      with:
        cmake-build-type: ${{ inputs.build-type }}
        install-security-tools: 'true'
        cache-prefix: 'rmtech-cpp-security'
        cmake-args: ${{ inputs.cmake-args }}
    
    - name: Configure CMake
      run: |
        cmake -B ${{ inputs.build-dir }} \
          -S ${{ inputs.source-dir }} \
          -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
          ${{ inputs.cmake-args }}
    
    - name: Run clang-tidy
      run: |
        find ${{ inputs.source-dir }} -name '*.cpp' -o -name '*.cc' -o -name '*.h' -o -name '*.hpp' | \
          xargs clang-tidy -p=${{ inputs.build-dir }} --config-file=.clang-tidy 2>&1 | \
          tee clang-tidy-report.txt
      continue-on-error: true
    
    - name: Run cppcheck
      run: |
        cppcheck --enable=all \
          --suppress=missingIncludeSystem \
          --xml --xml-version=2 \
          --output-file=cppcheck-report.xml \
          ${{ inputs.source-dir }}
      continue-on-error: true
    
    - name: Build
      id: build
      run: |
        cmake --build ${{ inputs.build-dir }} --config ${{ inputs.build-type }}
        echo "status=success" >> "$GITHUB_OUTPUT"
    
    - name: Generate C++ SBOM
      run: |
        syft ${{ inputs.build-dir }} -o cyclonedx-json=cpp-build-sbom.json
    
    - name: Prepare artifacts
      id: artifact
      if: inputs.upload-artifacts
      run: |
        ARTIFACT_NAME="cmake-build-${{ github.run_number }}"
        echo "name=$ARTIFACT_NAME" >> "$GITHUB_OUTPUT"
    
    - name: Upload build artifacts
      if: inputs.upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: |
          ${{ inputs.build-dir }}
          clang-tidy-report.txt
          cppcheck-report.xml
          cpp-build-sbom.json
        retention-days: 7