name: Create GitHub Release
description: Download artifacts and create GitHub release with SBOM, provenance, and Trivy reports

inputs:
  github_token:
    description: 'GitHub token'
    required: true
  image_digest:
    description: 'Container image digest'
    required: false
    default: ''
  image_name:
    description: 'Container image name'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    # Download required artifacts
    - name: Download source SBOMs
      uses: actions/download-artifact@v4
      with:
        name: source-sboms
        path: artifacts/source-sboms/
    
    - name: Download container attestations (has provenance + container SBOMs)
      uses: actions/download-artifact@v4
      with:
        name: container-attestations
        path: artifacts/container-attestations/
    
    - name: Download Trivy scans
      uses: actions/download-artifact@v4
      with:
        pattern: trivy-scan-results-*
        path: artifacts/trivy/
    
    # Organize and rename files
    - name: Prepare release files
      shell: bash
      run: |
        mkdir -p release
        VERSION=${GITHUB_REF_NAME#v}
        
        # Provenance
        cp artifacts/container-attestations/provenance.json release/provenance.json
        
        # Container SBOMs from attestations
        cp artifacts/container-attestations/container-sbom*.json release/ 2>/dev/null || true
        
        # Source SBOMs
        cp artifacts/source-sboms/*.json release/ 2>/dev/null || true
        
        # Rename all SBOMs to end with .sbom.json
        cd release
        for f in *sbom*.json; do
          [[ "$f" == *.sbom.json ]] || mv "$f" "${f%.json}.sbom.json"
        done
        
        # Consolidate Trivy reports
        cp ../artifacts/trivy/*/*.json . 2>/dev/null || true
        
        echo "Release files:"
        ls -la
    
    # Generate Release Report
    - name: Generate release report
      shell: bash
      run: |
        cat > release/RELEASE_REPORT.md << 'EOF'

        ## Release ${GITHUB_REF_NAME#v}      
        ### Security Summary
        - SLSA Provenance Generated
        - Container Signed with Cosign
        - SBOMs Generated (4 files)
        - Trivy Scan Completed
        
        ### Container Details
        - Image: ${{ env.IMAGE_NAME }}
        - docker pull ${{ inputs.image_name }}@${{ inputs.image_digest }}
        EOF
    
    # Add Summary Report
    - name: Add job summary report
      shell: bash
      run: |
        cat >> "$GITHUB_STEP_SUMMARY" << 'EOF'
        # Release Report
        
        Successfully created release with:
        - SBOMs:
        - Provenance: 
        - Trivy Report:
        
        [View Release](https://github.com/${{ github.repository }}/releases/tag//${{ github.ref_name }})
        EOF

    # Create GitHub Release titled "Release X.Y.Z"
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }} 
        generate_release_notes: true
        files: release/*.json
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}